import json
from pathlib import Path
P=Path(__file__).resolve().parents[1]/'out'
c=json.loads((P/'billing-investigation/candidates.json').read_text());e=json.loads((P/'billing-investigation/evidence.json').read_text());d=json.loads((P/'refit-500/data.json').read_text())
by={v['event_key']:v for v in e['events']};es=[by[v['event_key']] for cyc in d['cycles'] for v in cyc['events']]
audit=json.loads((P/'billing-investigation/observation-audit.json').read_text())
lines=['# Codex 额度计费机制调查','','## 当前结论','','尚未识别出唯一、可验证的完整扣量公式。现有证据支持优先修正测量方式，而不是继续把训练误差最低的参数当作真实费率。用户确认基本只在本机使用，共享额度的外部消耗暂列次要可能性。','','有一个不可绕过的数学限制：只有百分比时，将所有价格与周容量同时乘同一个常数，预测完全相同。$500/$100 是用户指定的美元锚点；没有独立账单或公开周信用点总额，不能从百分比证明这两个绝对金额。','','## 官方能确认的部分','','[官方 Codex 定价](https://learn.chatgpt.com/docs/pricing)给出 token 信用点率：','','| 每百万 token | 输入 | 缓存输入 | 输出 |','|---|---:|---:|---:|','| Sol | 100 | 10 | 500 |','| Terra | 50 | 5 | 300 |','| Luna | 5 | 0.5 | 30 |','| Astra | 250 | 25 | 1250 |','','[官方 Speed 文档](https://learn.chatgpt.com/docs/agent-configuration/speed)说明 GPT-5.6 与 Astra fast 使用 2.5 倍信用点；API priority 的定价另算。信用点表是可核实基准，但本次没有找到 Plus=$100、Pro5×=$500 的固定每周美元容量承诺，也没有从 auto-review 文档确认其扣量费率。审批 auto-review 不应与 GitHub Code Review 混同。','','## 本地核对结果','','- 只读提取 13,610 条范围内用量事件和 15,556 条观测，包含归档 rollout；沿用生图前 9,067 条拟合事件。','- 其中 9,038 条能匹配到当前保留的原始累计 token 记录；29 条未能匹配，保留原数据库值，没有猜测补齐。','- 匹配记录中 6 条数据库全零事件仍对应非零 last_token_usage，原因未定，没有擅自恢复或改写生产数据库。','- 同时间、相同 token 的非零跨 key 重复未发现。累计 token 差与 last_token_usage 的不一致主要是累计计数器回退，未发现正向缺口。','- 已匹配的样本均没有超过 272,000 输入 token；因此该阈值以上的长上下文溢价不能解释本次偏差。','- 所有有来源的 fast 标记均为 local-log 请求设置；没有 response 档位证据。未标明仍按 non-fast，仅作为延续假设。','- 各周期有效原始观测合计出现 133 次下降，最大 3 点；例如 62%→59% 相隔 4.159 秒，67%→65% 相隔 32.09 秒。普通单调累计扣费加单一取整函数无法产生这种下降；但仅凭下降无法区分陈旧快照、并发、退款或服务端调整。','- 单次新额度读取仍只有整数水位、重置时间和套餐等字段，没有剩余 token 或周美元余额。已保存去除账号标识的 fresh-baseline.json。','','## 候选机制复测','','以下均使用同一数据快照和原有首点差分累计目标；每类选择训练误差最低的 auto-review 方案。LOCO 为每次留出一个完整周期后的预测误差，参数可能因少数模型样本稀疏而不稳定。新增参数改善训练拟合不等于确认存在该费用。','','| 候选机制 | 最低训练 RMSE（百分点） | 对应整周期留出 RMSE | auto-review |','|---|---:|---:|---|']
labels={'base':'各模型固定倍率','request':'额外拟合每模型每次调用固定费','unknown':'未标明 fast 单独拟合','fastfree':'fast 费率单独拟合','reasoning':'额外拟合 reasoning token 系数','reviewfree':'auto-review 单独拟合系数'}
for kind,name in labels.items():
 best=min([v for v in c['candidates'] if v['kind']==kind],key=lambda v:v['all']['rmse']);v=best['all'];lines.append(f"|{name}|{v['rmse']:.3f}|{v['locoRMSE']:.3f}|{best['review']}|")
lines+=['','- 18 个结构候选（6 类×3 个 review 假设）和 33 个时间偏移候选（−120 秒到 +120 秒）都已运行。','- token 时间整体提前/延后不能统一修复：全样本最佳是纳入未来约 60 秒内已记录的调用，RMSE 约 1.457；但 Pro 子集偏好接近 0 秒，说明没有证据支持一个通用 60 秒结算规则。正偏移测试没有补采区间末尾之后的事件，因此仅为诊断。','- 每次调用固定费用模型训练 RMSE 可降至 1.021，但留出周期 RMSE 为 2.625；不能据此宣布有固定手续费。','- 放开 fast 后，免费 review 假设下拟合 Sol fast/non-fast≈2.08，Astra≈2.36；与当前官方 2.5 不同，更可能混合了历史、标记与观测问题，不能覆盖官方规则。','- 各候选即使允许非物理的负初始偏移来放宽约束，完整样本仍无 ±1 点可行解；这比强制非负初始用量更宽松，故不可行结论不依赖严苛基线限制。','','## 最有价值的下一步采样','','真正要区分计费机制，需要测量可归因的扣量增量。继续把所有历史百分比直接当账单累加，收益很低。以下为实验规范，未自动启动额外模型调用或长期后台任务。','','1. **额度测量独立于模型流。**每个实验块开始/结束，通过同一额度接口取新快照，记录抓取开始/结束时间、pool、plan、reset、整数百分比；不要拿旧任务附带的 rate_limits 当唯一真值。','2. **单模型、单档位、单任务运行。**暂停其他会使用同一池的任务，先完成 Sol non-fast，再做 Astra/Luna/Terra 与 fast 对照；每块保存原始 token、请求设置和可获得的服务端档位证据。','3. **等待结算稳定。**任务结束后重复读取独立水位，直到稳定；记录稳定所需时长，不事先假定固定延迟。旧水位回退保留原始值，不能取历史最大值后当精确观测。','4. **先求相对费率，不强求美元。**测量 token 信用点预测与实际百分比增量的比率，并用留出的重复实验验证。未知绝对容量始终保留一个缩放自由度。','5. **auto-review 做成对对照。**在主模型、档位和任务规模尽量相同时，比较有审批调用和无审批调用的实验块，回归 reviewer token 的额外贡献。不要为了实验诱发危险操作或修改安全策略。','6. **辨识缓存和固定费用。**设计总 token 接近但请求次数不同的两组任务，以及总输入接近但缓存比例不同的两组任务；否则输入/缓存/次数高度相关，固定费用和 token 费率会互相替代。','7. **设精度门槛。**两个四舍五入端点的差最多约有 1 点误差。仅消耗 5 个百分点的实验，单靠端点取整就可能有约 20% 相对误差；若希望约 5% 的单块分辨率，需要约 20 点跨度，或采用多次独立重复降低不确定性。优先利用实际工作采样，不刻意烧额度。','','验收标准：一套预先固定的参数，在未参与拟合的实验块中，按已验证的取整/稳定水位规则能得到非空容量交集；多个模型与档位重复后仍成立。满足前只称为候选模型。','','## 文件与复现','','- `node scripts/investigate-codex-billing.cjs`：只读提取 token 与观测元数据，不导出提示词、凭证或 HTTP 原文。','- `python scripts/study-codex-billing.py`：结构及时间对齐候选比较。','- `python scripts/report-billing-investigation.py`：生成本报告。','- 原始用量数据库与挂件估价逻辑未修改。']
(P/'billing-investigation/report.md').write_text('\n'.join(lines),encoding='utf-8')
print(P/'billing-investigation/report.md')
